
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kess-io-v1-function
  failurePolicy: Fail
  name: mfunction.kb.io
  rules:
  - apiGroups:
    - core.kess.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kess-io-v1-library
  failurePolicy: Fail
  name: mlibrary.kb.io
  rules:
  - apiGroups:
    - core.kess.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - libraries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kess-io-v1-runtime
  failurePolicy: Fail
  name: mruntime.kb.io
  rules:
  - apiGroups:
    - core.kess.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runtimes
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kess-io-v1-function
  failurePolicy: Fail
  name: vfunction.kb.io
  rules:
  - apiGroups:
    - core.kess.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kess-io-v1-library
  failurePolicy: Fail
  name: vlibrary.kb.io
  rules:
  - apiGroups:
    - core.kess.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - libraries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kess-io-v1-runtime
  failurePolicy: Fail
  name: vruntime.kb.io
  rules:
  - apiGroups:
    - core.kess.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runtimes
  sideEffects: None
