
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kess-io-v1-function
  failurePolicy: Fail
  name: mfunction.kb.io
  rules:
  - apiGroups:
    - core.kess.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kess-io-v1-library
  failurePolicy: Fail
  name: mlibrary.kb.io
  rules:
  - apiGroups:
    - core.kess.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - libraries

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kess-io-v1-function
  failurePolicy: Fail
  name: vfunction.kb.io
  rules:
  - apiGroups:
    - core.kess.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kess-io-v1-library
  failurePolicy: Fail
  name: vlibrary.kb.io
  rules:
  - apiGroups:
    - core.kess.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - libraries
