# permissions for end users to edit libs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lib-editor-role
rules:
- apiGroups:
  - core.kess.io
  resources:
  - libs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kess.io
  resources:
  - libs/status
  verbs:
  - get
