# permissions for end users to edit libraries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: library-editor-role
rules:
- apiGroups:
  - core.kess.io
  resources:
  - libraries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kess.io
  resources:
  - libraries/status
  verbs:
  - get
