# permissions for end users to view runtimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runtime-viewer-role
rules:
  - apiGroups:
      - core.kess.io
    resources:
      - runtimes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - core.kess.io
    resources:
      - runtimes/status
    verbs:
      - get
