# permissions for end users to edit runtimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runtime-editor-role
rules:
- apiGroups:
  - core.kess.io
  resources:
  - runtimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kess.io
  resources:
  - runtimes/status
  verbs:
  - get
