apiVersion: core.kess.io/v1
kind: Runtime
metadata:
  name: sample
spec:
  image: "python:3"
  command:
    - python
    - -m
    - http.server
---
apiVersion: core.kess.io/v1
kind: Runtime
metadata:
  name: sample2
spec:
  replicas: 2
  image: "python:3"
  command:
    - python
    - -m
    - http.server
