apiVersion: core.kess.io/v1
kind: Function
metadata:
  name: sample
spec:
  data:
    v1.py: |
      from kess import Function
      fn = Function()
      @fn.post("/")
      def sample():
          return {"fn": "sample", "version": "v1"}
    v2.py: |
      from kess import Function
      fn = Function()
      @fn.post("/")
      def sample():
          return {"fn": "sample", "version": "v2"}
    v3.py: |
      from kess import Function
      fn = Function()
      @fn.post("/")
      def sample():
          return {"fn": "sample", "version": "v3"}
